services:
  - name: my-node-app
    env:
      NODE_ENV: production
    buildCommand: npm run build
    startCommand: npm start
    websockets:
      type: wss
      enable: true
      sessionAffinity: external
